apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: deploy-webapp-taskrun
spec:
  # Use service account with git and image repo credentials
  serviceAccount: pipeline
  taskRef:
    name: deploy-webapp
  inputs:
    resources:
      - name: source-image
        resourceSpec:
          type: image
          params:
            - name: url
              value: image-registry.openshift-image-registry.svc:5000/example-webapp
  outputs:
    resources:
      - name: runtime-image
        resourceSpec:
          type: image
          params:
            - name: url
              value: quay.io/lanceball/example-webapp-runtime