apiVersion: v1
kind: Secret
metadata:
  name: basic-user-pass
  annotations:
    tekton.dev/docker-0: image-registry.openshift-image-registry.svc:5000
type: kubernetes.io/basic-auth
stringData:
  username: kubeadmin
  password: ehbg7-zu5i6-JKt7V-PvJsm