apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: production-webapp
  namespace: msa-day-ny
spec:
  template:
    metadata:
      labels:
        app: webapp
        tier: frontend
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/msa-day-ny/webapp-runtime
          resources:
            requests:
              cpu: 50m
              memory: 20Mi
          ports:
            - containerPort: 8080
